In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
data=pd.read_csv('hate_crime.csv')
print(data)

        incident_id  data_year        ori    pug_agency_name pub_agency_unit  \
0                43       1991  AR0350100         Pine Bluff             NaN
1                44       1991  AR0350100         Pine Bluff             NaN
2                45       1991  AR0600300  North Little Rock             NaN
3                46       1991  AR0600300  North Little Rock             NaN
4                47       1991  AR0670000             Sevier             NaN
...             ...        ...        ...                ...             ...
253771      1513747       2023  WY0190100        Green River             NaN
253772      1517229       2023  WY0130100             Casper             NaN
253773      1517231       2023  WY0110100           Cheyenne             NaN
253774      1519468       2023  WY0150000               Park             NaN
253775      1519469       2023  WY0110100           Cheyenne             NaN

       agency_type_name state_abbr state_name       division_name region_name  \
0                  City         AR   Arkansas  West South Central       South
1                  City         AR   Arkansas  West South Central       South
2                  City         AR   Arkansas  West South Central       South
3                  City         AR   Arkansas  West South Central       South
4                County         AR   Arkansas  West South Central       South
...                 ...        ...        ...                 ...         ...
253771             City         WY    Wyoming            Mountain        West
253772             City         WY    Wyoming            Mountain        West
253773             City         WY    Wyoming            Mountain        West
253774           County         WY    Wyoming            Mountain        West
253775             City         WY    Wyoming            Mountain        West

        ...              offender_race      offender_ethnicity victim_count  \
0       ...  Black or African American           Not Specified            1
1       ...  Black or African American           Not Specified            2
2       ...  Black or African American           Not Specified            2
3       ...  Black or African American           Not Specified            1
4       ...                      White           Not Specified            1
...     ...                        ...                     ...          ...
253771  ...                      White  Not Hispanic or Latino            1
253772  ...                      White  Not Hispanic or Latino            1
253773  ...                      White  Not Hispanic or Latino            1
253774  ...              Not Specified           Not Specified            1
253775  ...                      White  Not Hispanic or Latino            1

                                             offense_name  \
0                                      Aggravated Assault
1       Aggravated Assault;Destruction/Damage/Vandalis...
2       Aggravated Assault;Murder and Nonnegligent Man...
3                                            Intimidation
4                                            Intimidation
...                                                   ...
253771                                       Intimidation
253772                                 Aggravated Assault
253773                                        Shoplifting
253774                                  All Other Larceny
253775                                        Shoplifting

        total_individual_victims                       location_name  \
0                            1.0                      Residence/Home
1                            1.0  Highway/Road/Alley/Street/Sidewalk
2                            2.0                      Residence/Home
3                            1.0                      Residence/Home
4                            1.0                      School/College
...                          ...                                 ...
253771                       1.0         School-Elementary/Secondary
253772                       1.0             Parking/Drop Lot/Garage
253773                       0.0                 Grocery/Supermarket
253774                       1.0                      Residence/Home
253775                       0.0                   Convenience Store

                              bias_desc  victim_types multiple_offense  \
0        Anti-Black or African American    Individual                S
1                            Anti-White    Individual                M
2                            Anti-White    Individual                M
3                            Anti-White    Individual                S
4        Anti-Black or African American    Individual                S
...                                 ...           ...              ...
253771                      Anti-Jewish    Individual                S
253772  Anti-Arab;Anti-Islamic (Muslim)    Individual                S
253773           Anti-Jehovah's Witness      Business                S
253774                       Anti-White    Individual                S
253775                    Anti-Buddhist      Business                S

       multiple_bias
0                  S
1                  S
2                  S
3                  S
4                  S
...              ...
253771             S
253772             M
253773             S
253774             S
253775             S

[253776 rows x 28 columns]

In [8]:
#concise summary of dataframe
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 253776 entries, 0 to 253775
Data columns (total 28 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   incident_id                   253776 non-null  int64
 1   data_year                     253776 non-null  int64
 2   ori                           253776 non-null  object
 3   pug_agency_name               253776 non-null  object
 4   pub_agency_unit               7595 non-null    object
 5   agency_type_name              253776 non-null  object
 6   state_abbr                    253776 non-null  object
 7   state_name                    253776 non-null  object
 8   division_name                 253776 non-null  object
 9   region_name                   253776 non-null  object
 10  population_group_code         253109 non-null  object
 11  population_group_description  253109 non-null  object
 12  incident_date                 253776 non-null  object
 13  adult_victim_count            82700 non-null   float64
 14  juvenile_victim_count         80063 non-null   float64
 15  total_offender_count          253776 non-null  int64
 16  adult_offender_count          73219 non-null   float64
 17  juvenile_offender_count       73212 non-null   float64
 18  offender_race                 253776 non-null  object
 19  offender_ethnicity            253776 non-null  object
 20  victim_count                  253776 non-null  int64
 21  offense_name                  253776 non-null  object
 22  total_individual_victims      248651 non-null  float64
 23  location_name                 253776 non-null  object
 24  bias_desc                     253776 non-null  object
 25  victim_types                  253776 non-null  object
 26  multiple_offense              253776 non-null  object
 27  multiple_bias                 253776 non-null  object
dtypes: float64(5), int64(4), object(19)
memory usage: 54.2+ MB

In [13]:
#getting insight the null values in the dataframe
data.isna().sum()

incident_id                          0
data_year                            0
ori                                  0
pug_agency_name                      0
pub_agency_unit                 246181
agency_type_name                     0
state_abbr                           0
state_name                           0
division_name                        0
region_name                          0
population_group_code              667
population_group_description       667
incident_date                        0
adult_victim_count              171076
juvenile_victim_count           173713
total_offender_count                 0
adult_offender_count            180557
juvenile_offender_count         180564
offender_race                        0
offender_ethnicity                   0
victim_count                         0
offense_name                         0
total_individual_victims          5125
location_name                        0
bias_desc                            0
victim_types                         0
multiple_offense                     0
multiple_bias                        0
dtype: int64

In [17]:
#summary of statistics pertaining to the DataFrame columns
data.describe()

,incident_id,data_year,adult_victim_count,juvenile_victim_count,total_offender_count,adult_offender_count,juvenile_offender_count,victim_count,total_individual_victims
count,2.537760e+05,253776.000000,82700.000000,80063.000000,253776.000000,73219.000000,73212.000000,253776.000000,248651.000000
mean,4.045290e+05,2007.711320,0.749456,0.107216,0.949542,0.623090,0.128804,1.016645,0.989777
std,5.626399e+05,9.798864,1.089989,0.499702,1.298449,0.808085,0.531138,0.249848,1.131179
min,2.000000e+00,1991.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,6.347575e+04,1999.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000
50%,1.269305e+05,2007.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000
75%,1.945972e+05,2017.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000
max,1.522894e+06,2023.000000,146.000000,60.000000,99.000000,60.000000,20.000000,5.000000,147.000000

In [20]:
print ("Number of rows in the dataset  : " ,data.shape[0])
print ("Number of Columns in the dataset : " ,data.shape[1])
print ("Number of Features : \n" ,data.columns.tolist(), "\n")
print ("Unique values :  \n",data.nunique())

Number of rows in the dataset  :  253776
Number of Columns in the dataset :  28
Number of Features :
 ['incident_id', 'data_year', 'ori', 'pug_agency_name', 'pub_agency_unit', 'agency_type_name', 'state_abbr', 'state_name', 'division_name', 'region_name', 'population_group_code', 'population_group_description', 'incident_date', 'adult_victim_count', 'juvenile_victim_count', 'total_offender_count', 'adult_offender_count', 'juvenile_offender_count', 'offender_race', 'offender_ethnicity', 'victim_count', 'offense_name', 'total_individual_victims', 'location_name', 'bias_desc', 'victim_types', 'multiple_offense', 'multiple_bias']

Unique values :
 incident_id                     253776
data_year                           33
ori                              10710
pug_agency_name                   7110
pub_agency_unit                    713
agency_type_name                     8
state_abbr                          53
state_name                          53
division_name                       11
region_name                          6
population_group_code               20
population_group_description        20
incident_date                    12053
adult_victim_count                  27
juvenile_victim_count               17
total_offender_count                34
adult_offender_count                17
juvenile_offender_count             16
offender_race                        8
offender_ethnicity                   5
victim_count                         6
offense_name                       423
total_individual_victims            47
location_name                      156
bias_desc                          415
victim_types                        57
multiple_offense                     2
multiple_bias                        2
dtype: int64

In [22]:
# geting to know which year has more accident
data.value_counts('data_year')

data_year
2023    11858
2022    11766
2021    11014
2020     9958
2001     9730
1996     8789
2000     8217
1997     8105
2008     8039
1995     7949
1999     7940
1998     7889
2019     7869
2006     7715
2004     7684
2007     7623
1993     7604
2003     7539
2002     7485
2005     7411
2017     7327
2018     7176
1992     6662
2010     6628
2009     6612
2012     6592
2011     6299
2016     6270
2013     6044
1994     5953
2015     5843
2014     5597
1991     4589
Name: count, dtype: int64

In [24]:
data.duplicated().sum()  # Check for duplicate rows
data.isnull().sum()  # Count missing values in each column

incident_id                          0
data_year                            0
ori                                  0
pug_agency_name                      0
pub_agency_unit                 246181
agency_type_name                     0
state_abbr                           0
state_name                           0
division_name                        0
region_name                          0
population_group_code              667
population_group_description       667
incident_date                        0
adult_victim_count              171076
juvenile_victim_count           173713
total_offender_count                 0
adult_offender_count            180557
juvenile_offender_count         180564
offender_race                        0
offender_ethnicity                   0
victim_count                         0
offense_name                         0
total_individual_victims          5125
location_name                        0
bias_desc                            0
victim_types                         0
multiple_offense                     0
multiple_bias                        0
dtype: int64

In [25]:
data['offender_race'].fillna('Unknown', inplace=True)
data['offender_race'].isnull().sum()  # Verify no missing values remain

0

In [26]:
data.drop('offender_ethnicity', axis=1, inplace=True)

In [28]:
columns_for_removal = ['total_individual_victims', 'adult_offender_count', 
                       'juvenile_offender_count', 'adult_victim_count', 
                       'juvenile_victim_count']
data.drop(columns_for_removal, axis=1, inplace=True)

In [29]:
cols_to_drop = ['division_name', 'multiple_offense', 'multiple_bias', 'ori']
data.drop(cols_to_drop, axis=1, inplace=True)

In [31]:
data.drop('pub_agency_unit', axis=1, inplace=True)

In [32]:
data['incident_date'] = pd.to_datetime(data['incident_date'])

In [33]:
new_names = {'incident_id':'INCIDENT_ID', 'data_year':'DATA_YEAR',
             'pub_agency_name':'PUB_AGENCY_NAME', 'agency_type_name':'AGENCY_TYPE_NAME',
             'state_abbr':'STATE_ABBR', 'state_name':'STATE_NAME',
             'region_name':'REGION_NAME', 'population_group_code':'POPULATION_GROUP_CODE',
             'population_group_description':'POPULATION_GROUP_DESC',
             'incident_date':'INCIDENT_DATE', 'total_offender_count':'TOTAL_OFFENDER_COUNT',
             'offender_race':'OFFENDER_RACE', 'victim_count':'VICTIM_COUNT',
             'offense_type':'OFFENSE_NAME', 'location_type':'LOCATION_NAME',
             'prejudice':'BIAS_DESC', 'victim_types':'VICTIM_TYPES'}

data.rename(columns=new_names, inplace=True)